Sequel 5.9.0
The embedded version of knife-ec-backup has the following issue:

1: from
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/adapters/shared/postgres.rb:89:in
`<module:Postgres>'
/opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/adapters/shared/postgres.rb:89:in
`method': undefined method `new' for class `#<Class:BigDecimal>' (NameError)

The following change was discovered in the Sequel changelog:

https://github.com/jeremyevans/sequel/blob/master/CHANGELOG    === 5.9.0 (2018-06-01)
* Switch use of BigDecimal.new() to BigDecimal(), since the former is deprecated (jeremyevans)

Signed-off-by: Lincoln Baker <lbaker@chef.io>

Signed-off-by: Vinay Satish <vinay.satish@progress.com>